### ISSUE TITLE
vlan forwarder; Questions regarding integration

### ISSUE THREAD

**Issue by ljkiraly** [networkservicemesh/sdk#1009]
## Question

This issue collects the questions regarding vlan forwarder integration:

1. Is the VLAN mechanism really needed?
2. Can be accepted the behavior of this forwarder? The forwarder creates  a VLAN interface and move that into the NSC. There is no other interface created in NSE, neither in forwarder. The NSE role is to provide the IP context also the base interface name and the vlan ID.
3. Can you create the cmd-vlan-forwarder repository and some repository for the code of an NSE (similar to icmp-responder) supporting the mechanism and providing the point2multipoint IPAM?   

## Details for question no. 2 
To provide a vlan interface the following solution were taken in consideration:
The interface dropped in NSC should be any kernel interface and the forwarder should create the vlan interface in main namespace for the remote connection. This would mean an extra hop and complicates the link supervision from NSC namespace, which are cons from our perspective. For further details see the following gist: [Interfaces created by VLAN forwarder](https://gist.github.com/ljkiraly/c219399cc4a66bfdec473cd459f9ac42)

Currently both the local and remote mechanism is VLAN which is a discrepancy and the remote mechanism can be NONE.

## Related Issues and PRs

Repository | Issue | Pull Request
------------ | ------------- | ------------
sdk |  #951 | #953 
api | [api#97](https://github.com/networkservicemesh/api/issues/97) | [api#98](https://github.com/networkservicemesh/api/issues/98) 
sdk-kernel | [sdk-kernel#246](https://github.com/networkservicemesh/sdk-kernel/issues/246) | [sdk-kernel#258](https://github.com/networkservicemesh/sdk-kernel/issues/258)

**Comment by ljkiraly** [comment]
1/ The VLAN mechanism was added in order to force the nsmgr to select the VLAN forwarder. If the planned forwarder selection is in place can be placed with KERNEL mechanism. Do you have any other suggestion?

**Comment by edwarnicke** [comment]
@ljkiraly I appreciate your patience :)

The vlan forwarder came up in the discussions at the SRIOV for NSEs conversation, and I it was mentioned that this is actually two cases:

1. **vlan-trunking**
  Many existing (and future) CNFs expect vlan tags to identify different 'vWires' coming in on a common interface (ie, vlan trunking).  The idea being that your 'Forwarder' would pop a vxlan tag for the vWire, and push a vlan tag before passing it on the single interface to the CNF.  In essence, the 'vlan' on that trunk interface is an extension of the vWire.
2. **vlan remote mechanism*
   When connecting a Client to a physical network bridge domain, the remote mechanism might be 'vlan' meaning push pop of vlan encap on the wire. 

For **vlan-trunking** case I would suggest we enhance the kernel mechanism to have two optional parameters:
- 'canVlanTrunk' sent from the Forwarder to the NSE if it can support vlan trunking. (note: I hate the name 'canVlanTrunk' here, please please please think of something better :) )
- 'vlan' sent initially from the NSE to the Forwarder in response to 'canVlanTrunk' if that's the preference of the NSE.

If an NSE sends back a 'vlan' parameter for the kernel interface, the Forwarder should look at the [InterfaceName](https://github.com/networkservicemesh/api/blob/main/pkg/api/networkservice/mechanisms/kernel/constants.go#L40) parameter:

If it does not already have an interface by that name for that NSE, it should create it.

Then the 'vlan' should be trunked for that vWire across the named interface.

In this way, we should be able to get the 'vlan trunking' case as a logical extension of the kernel mechanism.  Which is proper as the local mechanism is still a kernel interface.

For the **vlan remote mechanism** it does make sense to define a remote mechanism for vlan tags as an encap type.
 I think there may have been a notion that this required a 'vlan-forwarder' because of the question of 'But where is the NSE'
In the case (like this one) where there is no dataplane for the Network Service on a Node, its fully appropriate to run a 'control plane' NSE that registers directly with the registry.   Example:

- Say we have the NetworkService 'finance-bridge-domain' being provided by the physical network.
- An NSE can be run on a Pod, registering itself directly (rather than via the NSMGR) for that Network Service.
- When a Client requests the 'finance-bridge-domain', its local NSMGR finds a URL for the Pod of the NSE in the Registry
- The NSMGR sends the Request to the NSE
- The NSE maps the Network Service Name 'finance-bridge-domain' to a vlan tag (say 12) and returns the remote mechanism of type vlan (class remote) with tag 12 as its parameter.
- The NSMgr plumbs in whatever the local mechanism is for the client in such a way it will arrive at the physical network on vlan 12.

If this is the problem you are trying to solve, and this is an acceptable solution, I don't think we need a vlan-forwarder as a separate thing, we can simply have a vlan remote mechanism implemented by any forwarder.

@ljkiraly Do these make sense?  Are those really the two use cases you are looking to solve?  Do the solutions seem both usable and elegant to you?

**Comment by ljkiraly** [comment]
Thanks @edwarnicke!

I had concerns regarding the vlan-forwarder myself.
For the **vlan remote mechanism** case I really like the idea of running a 'control plane' NSE that registers directly with the registry. Now I understand your point and most probably what I was looking for is the **remote vlan mechanism** support.
What still not clear regarding this last point in your example: 
> The NSMgr plumbs in whatever the local mechanism is for the client in such a way it will arrive at the physical network on vlan 12." 

- Is the nsmgr which set this or the local forwarder?

The **vlan-trunking** case is also interesting, but I would go for the remote case first. Instead of 'canVlanTrunk' I would propose 'hasVlanTrunkingSupport' or 'hasVlanTrunking'.

**Comment by edwarnicke** [comment]
> The NSMgr plumbs in whatever the local mechanism is for the client in such a way it will arrive at the physical network on vlan 12."

That was me, writing far to fast... you are correct, its the Forwarder that does the plumbing.

**Comment by edwarnicke** [comment]
> The vlan-trunking case is also interesting, but I would go for the remote case first. Instead of 'canVlanTrunk' I would propose 'hasVlanTrunkingSupport' or 'hasVlanTrunking'.

@ljkiraly I like where this is going... I think we probably want to set a pattern here, as we are likely going to see other analogous cases.

So far of your suggestions I like 'hasVlanTrunking' the best... 'has' could be a prefix for general use.
You suggestion 'hasVlanTrunkingSupport'  spurred an idea.  By itself its to long, but the word 'support' is clear.
It got me thinking... perhaps we use 'supports' as the prefix, and append the parameter we support.

So in the example at hand, the parameter we support is 'vlan' and so the parameter to indicate we support it would be 'supportsVlan'.

Thoughts?

**Comment by ljkiraly** [comment]
> It got me thinking... perhaps we use 'supports' as the prefix, and append the parameter we support.
> So in the example at hand, the parameter we support is 'vlan' and so the parameter to indicate we support it would be 'supportsVlan'.

Yes, 'supportsVlan' is short and clear.

**Comment by edwarnicke** [comment]
Oh good :)  @ljkiraly would you like to push a PR to add that to the API for the kernel mechanism helpers?

**Comment by ljkiraly** [comment]
Thanks @edwarnicke! I am to update the kernel mechanism helper to add these 'supportsVlan' and 'vlan' parameters.
Still have concerns about the trunking and plumbing of these vlan interfaces. What did you mean by this?
> the 'vlan' should be trunked for that vWire across the named interface

What I would like to avoid to have extra MAC addresses for the interim interfaces.

**Comment by edwarnicke** [comment]
> What I would like to avoid to have extra MAC addresses for the interim interfaces.
@ljkiraly Could you say more about your concerns here?  I don't quite follow.

**Comment by ljkiraly** [comment]
@edwarnicke If we have an interface created in NSC that will have a MAC address. If this is bridged with a vlan interface than the base of vlan interface will have an other MAC, right? These addresses will be visible on the network connected and can be filtered (by openstack for example).

**Comment by edwarnicke** [comment]
@ljkiraly Lets talk through it slowly... if I send an ethernet frame from the NSC to the NSE (local case)

1. NSC sends ethernet frame.  It has src=nsc_mac, dst=nse_mac
2. The frame arrives at the Forwarder.
3. The Forwarder pushes a 802.1q tag (src and dst unchanged)
4. The frame arrives at the NSE

Does that match your expectation?

**Comment by ljkiraly** [comment]
@edwarnicke Forgive my incomprehension in this. I was stuck to creating bridges and interfaces :) I'm not familiar with vpp, but I guess there is support for pushing vlan tag.
I also apologize for the late answer I had to reinstall my computer.

**Comment by edwarnicke** [comment]
@ljkiraly Ah... mechanically pushing or popping a vlan need not have anything at all to do with bridging.   

![image](https://user-images.githubusercontent.com/1455208/126910092-6b9caa1e-6af2-42dd-ba7b-7dd723b59e0c.png)

Basically shows the mechanics... it involves just pushing 4 bytes between the src mac and the ethertype :)

**Comment by ljkiraly** [comment]
@edwarnicke Yes, that is clear. Just the cheapest way was to have this modification done by the kernel instead of doing this by packet processing.
I created a new PR  api#109 for updated kernel mechanism helper.

**Comment by edwarnicke** [comment]
@ljkiraly Apologies... I've lost track a bit... what do you see as our next steps here?

**Comment by ljkiraly** [comment]
@edwarnicke Yes, that is my fault. I was on vacation in last 3 weeks and I had no plan what should be done. 

I originally planed to start with **vlan remote mechanism** case, but after digging in it a bit I realized that the local **vlan-trunking** case is easier. So I prefer to continue with **vlan-trunking** case:
- I will add support for vlan tag push/pop in vpp-forwarder. I did not checked yet, but you know for sure if govpp is supporting [VLAN Tag Rewrite](https://wiki.fd.io/view/VPP/Command-line_Interface_(CLI)_Guide#VLAN_Tag_Rewrite), if not that must be added also.
- Add environment variable to  `nse-icmp-responder-vpp` and code to process 'supportsVlan' parameter and pass 'vlan' parameter.


After that I am going to focus on remote mechanism, and I'll implement the suggested changes:
- Create new vlan mechanism
- Create new NSE with vlan mechanism support and registering directly with the registry.
- Support for remote vlan mechanism in vpp-forwarder.
(You mentioned earlier that any forwarder - vpp and sriov - should support the remote vlan mechanism. Is that really required? The support for vlan remote mechanism in vpp-forwarder would be enough from my part.)


I am to create issues for these if you have no objection or other suggestion.

**Comment by ljkiraly** [comment]
Hello @edwarnicke,

I've implemented the remote mechanism support in vpp forwarder.
Now I'm facing with an address resolution problem. It is caused by having different internal MAC address inside of NSM client (NSC) namespace than the base interface address. The ARP packets are dropped.

* The 'nsm-1' interface configuration in NSC:

```
# ip a s nsm-1
23: nsm-1@if22: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 9000 qdisc noqueue state UP qlen 1000
    link/ether 1e:0d:e0:5f:2a:a3 brd ff:ff:ff:ff:ff:ff
    inet 172.10.0.1/24 brd 172.10.0.255 scope global nsm-1
...
```

* In forwarder
** host-interface created inside vpp 'host-eth1' (Ethernet address 00:00:00:01:01:01)
** 'host-eth1.5' is a sub-interface of host-interface 'host-eth1' with outer vlan id 200
** 'host-server-891443ce' is the veth pair of 'nsm-1' interface
** 'host-eth1.5' and 'host-server-891443ce' are put in Layer2 cross-connect mode:

```
vpp# show mode
l3 local0
l3 host-eth1
l2 xconnect host-server-891443ce host-eth1.5
l2 xconnect host-eth1.5 host-server-891443ce
```

I created a VLAN interface (MAC 00:00:00:01:01:04) on a base interface connected to 'eth1'. The connection between this external VLAN interface and 'nsm-1' interface can be established when the 'eth1' interface is on promiscuous mode. Otherwise the 'eth1' interface will drop the ARP response.

```
# tcpdump -ni eth1 -en vlan

12:01:47.096686 1e:0d:e0:5f:2a:a3 > ff:ff:ff:ff:ff:ff, ethertype 802.1Q (0x8100), length 46: vlan 200, p 0, ethertype ARP, Request who-has 172.10.0.2 tell 172.10.0.1, length 28
12:01:47.097565 00:00:00:01:01:04 > 1e:0d:e0:5f:2a:a3, ethertype 802.1Q (0x8100), length 46: vlan 200, p 0, ethertype ARP, Reply 172.10.0.2 is-at 00:00:00:01:01:04, length 28
```

I tried to add secondary MAC to host-interface, but that doesn't help. Do you have any idea how to get this working without setting promiscuous mode? I missed something?
