### ISSUE TITLE
Simplify healing - determinate reselect state for whole chain

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1454]
## Steps to reproduce

1. deploy nsm
2. deploy nse1 with service ns1
2. deploy nse2 with service ns1
3. deploy nsc
4. nsc connects to nse1
5. nse1 dies
6. nsc reselects nse
7. client's nsmgr misses close from reselect

## Expected Behavior

All downstream components correctly handle reselect on next request from the nsc.

## Current Behavior

All downstream components  do something non-deterministic. (i.e. some component like forwarder may try to restore connection, some component may just refresh the connection)

## Context

See at https://github.com/networkservicemesh/sdk/blob/6fa2f68d5532ace9f0d7c4edccb1e069d35c15df/pkg/networkservice/common/heal/eventloop.go#L131
See at 
https://github.com/networkservicemesh/sdk/blob/6fa2f68d5532ace9f0d7c4edccb1e069d35c15df/pkg/networkservice/common/begin/event_factory.go#L102

## Initial ideas

1. Remove here path https://github.com/networkservicemesh/sdk/blob/6fa2f68d5532ace9f0d7c4edccb1e069d35c15df/pkg/networkservice/common/begin/event_factory.go#L107 and then all downstream components   will think that it is a new connection
2. Add something into request proto to determidate reselect state by downstream components

## Defenition of done

- [x] Investigate the problem and suggest options on resolve the problem with pros/cons.
- [ ] Get approve from @edwarnicke 
- [x] Implement the solution.
- [ ] Pass linters/code review ~2h
- [ ] Pass integration tests. ~14h

**Comment by d-uzlov** [comment]
# Current behavior

From what I can understand, current behavior with trying to restore the old connection on reselect is an attempt to prevent resource leaks.

If Close call goes through all apps in the connection path, then all elements clear data about connection, and a new request is treated as a completely new request, with proper reselect.
If Close call doesn't reach some apps, then reselect request is treated as a refresh.
If Close call didn't reach some app and the app has restarted, then we try to restore the connection, based on assumption that this is a refresh request call.

We can change a reselect request in some way to properly indicate that this is a reselect request.
This will solve the issues with lost Close case. It will not matter is Close reached all apps in the path or not, all apps will treat the request as reselect.

There is an issue with this approach: if the Close didn't reach the app and we create a new connection instead of restoring the old one, the app will leak resources.

If the reselect request goes through the same path, then we can try to detect the reselect and try to clear resources.
If reselect request goes through a different path, then there is not much we can do during the request.

# Open questions

1. How can a server understand that some request is a reselect?
2. Should we try to clear resources on a reselect after failed Close? How?

Second question is the hard one. If we decide to ignore it, the first one has several easy solutions.

# Option 1 for reselect

Simply clear connection path on reselect (except for the first path segment).
Then `updatePath` will generate a new IDs for all path segments, and all chain elements will treat the request as a completely new connection.

https://github.com/networkservicemesh/sdk/blob/6fa2f68d5532ace9f0d7c4edccb1e069d35c15df/pkg/networkservice/common/begin/event_factory.go#L107
```go
request.GetConnection().Path.PathSegments = []*networkservice.PathSegment{request.GetConnection().Path.PathSegments[0]}
```

Pros:
- No changes in other chain elements needed.

Cons:
- Reselect looks like a new request
- Doesn't solve resource leaks
- Current attempt to prevent resource leaks will no longer work

# Option 2 for reselect

Add a new `reselect` field to request.

https://github.com/networkservicemesh/api/blob/5d372416a0b4b0d70d37a801e6d24fe37cf5c432/pkg/api/networkservice/networkservice.proto#L28

```proto
message NetworkServiceRequest {
  connection.Connection connection = 1;
  repeated connection.Mechanism mechanism_preferences = 2;
  bool reselect = 3;
}
```
```go
...
if request.reselect {
    clearOldResources()
}
...
```

Pros:
- Distinct reselect (an ability to clear resources)

Cons:
- Requires changes in all chain elements with state
- Change in API
- Doesn't help to clear resources if we go through a different path on reselect

**Comment by d-uzlov** [comment]
# Current behavior

If Close reaches all apps in path, it clears all caches, and reselect works as expected.

If Close doesn't reach some apps, those apps try to restore old connection to avoid resource leaks.
Therefore, reselect doesn't work.

# Solution 1

Clear request path.
Then `updatePath` will create new IDs, there will be no caches for new ID, so we are guaranteed to get proper reselect.
The only element of the path we need to preserve is the first one.

I tested this solution using sandbox tests, and it seems to be working.
The resources will leak, though, until timeout.

# Solution 2

Create a new parameter in request: `reselect`.
```proto
message NetworkServiceRequest {
  connection.Connection connection = 1;
  repeated connection.Mechanism mechanism_preferences = 2;
  bool reselect = 3;
}
```
This way any app in the path will know that it should not try to restore anything.
Maybe we could also try to call Close, if we missed it earlier, and clear our resources and resources in apps down the path.
Though, it will not work in many cases, because we are unlikely to go to the same app on reselect.

Major downside is that it would require a lot of changes. Basically in every chain element that stores any info about the connection.

**Comment by denis-tingaikin** [comment]
Seems like done
