### ISSUE TITLE
expire chain element with multiple registries

### ISSUE THREAD

**Issue by or-adar** [networkservicemesh/sdk#1472]
Hi!
I was going over "expire" chain element in registry
and noticed that it should call Unregister after configurable period of time,
But it looks like it could be problematic as the gRPC connections can change from one instance to the other over time (in multi registries setup).
So when registry client of NSE changes connection to a different instance the old registry instance might think that the NSE is down and Unregister it.
Am I missing something? in multi registries setup - registry can leak resources or Unregister endpoints that are up and running?

**Comment by edwarnicke** [comment]
@or-adar The presumption is that if you have multiple registries there is some consistent store behind them.  So at the *design* level, if I refresh he NSE with a different registry instance, the caking store will be updated with a new expiration time and the previous registry can know that and not expire.

All of that said, *implementation* bugs can happen, and if you think you see one, we'd be very interested in hearing about it :)

**Comment by or-adar** [comment]
@edwarnicke Appreciate your response!
I can't say for sure I found any issues, I'm expirimanting with the sdk and forked registry to explore other stores (that are not memory or etcd based).

could you maybe refer me to how the old registry know that it doesn't have to expire?
I'm going over the expire chain element code: https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/expire/nse_server.go
but I don't think I find any indication to any logic that is being aware of the new expiration time that was updated by the new registry instance.

**Comment by edwarnicke** [comment]
@denis-tingaikin Thoughts?

**Comment by denis-tingaikin** [comment]
@or-adar Hello, yes in theory leaks are possible for multiple **registry-memory** instances on the k8s cluster.

In **registry-k8s** we're using versions check https://github.com/networkservicemesh/sdk-k8s/blob/main/pkg/registry/etcd/nse_server.go#L140

Have you faced with some problems during using NSM?

**Comment by or-adar** [comment]
Hi @denis-tingaikin,
I'm not facing any particular issues with registry-k8s,
as I'm expirimanting with the sdk and forked registry to explore it with postgres
and now that I see what you did with it in skd-k8s, I think that I'll have to translate that logic to my needs as "resourceVersion" is maintained by k8s on each modification, and you just rely on that in k8s-sdk.

the only thing that bothers me is what theoretically enforces Unregister & Register calls to occur in the expected order?
meaning that some Endpoint register to registry A, 
then it switched to register on registery B,
a timeout occured and Unregister is invoked by registry A, but right then,
the Endpoint switched to registry A and registered itself, 
and if no order is enforced the Register logic could theoretically execute before Unregister and update the "versions" map with the last version,so when Unregister deletes the the CR it'll use a valid version.
I could be wrong and this could never happen, but I would like to know your take.

**Comment by denis-tingaikin** [comment]
I very like that you're looking for corner cases in registry ;) 


OK, let's consider that use-case.

Steps:

1. deploy nsm ifra without registry
2. deploy registry k8s A
3. deploy registry k8s B
4. deploy nse
5. nse registers in registry A
6. wait nse registration refresh
7. nse registers in registry B
8. nse  forces registration  in registry A

Now we have a few variants:

variant 1:
9. registry A is going to unregister the  of nse by timeout
10. registry A cannot do that due to version check
11. registry A receives a new registration from the nse and registers it with new version


variant 2:
9. registry A receives a new registration from the nse and registers it with new version
10 .registry A cancels expiration job for the nse.


Note:

1. we're using serializing of registers by name of the nse. See at https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/begin/doc.go
2. expire registry server cancels scheduled jobs https://github.com/networkservicemesh/sdk/blob/main/pkg/registry/common/expire/nse_server.go#L97

**Comment by denis-tingaikin** [comment]
@or-adar Make sense?

Also, if you have any ideas to improve expiration strategy for nsm registries feel free to share your thoughts. We're open for cool solutions ;)

**Comment by or-adar** [comment]
Got it! makes sense now.
Thanks for explaining :)

**Comment by denis-tingaikin** [comment]
@or-adar OK, feel free to reopen it if you get any new questions
