### ISSUE TITLE
Parallel SDK testing

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#1491]
Add flag parallel

See at https://github.com/networkservicemesh/integration-tests/commit/482aba094c59de511be3f47fde7a79d9cc73c3f2

**Comment by denis-tingaikin** [comment]
TODO:

1. `go test -count 1  -parallel 4 --race ./...`
2. add t.Parallel() // t.Skip() 

Stages:
1. Add t.Paralell() for all tests where is not imported 'sandbox'.
2. Add t.Paralell() for all tests where is 'sandbox'. 
3. Investigate failing tests.

**Comment by dualBreath** [comment]
We have done research on reducing test execution time and tested several approaches, but without success.

The first approach with the addition of `t.Parallel()` allows us to speed up by about 30 seconds, but also causes a number of problems. Comparing to overall time and problems severity we decided to do not apply this solution.
The main problem with `t.Parallel()` is the inability to use goroutine leak checking for each test case, because it detects other tests running in parallel as leaks. The tests become very unstable and fail from time to time, so stabilization for all tests will take a significant amount of time. This may also lead to removing `t.Parallel()` from many tests to stabilize them, which also means that this approach cannot give us a significant time gain.

To avoid problems with using goroutine leak checking with `t.Parallel()` we also tried to change the goroutine leak checking for each tests to goroutine leak checking for all package. For this purpose we applied solution with 

```
func TestMain(m *testing.M) {
	goleak.VerifyTestMain(m)
}
```
Using this approach we can use `t.Parallel()` without a problems with goroutine leak checking. But some tests use a specific goroutine release test, so this is still a problem and won't work with `t.Parallel()`. Most importantly here we will lose the readability of errors, because with this change we can only see that the error occurs in some package, and it is impossible to determine the exact name of the failed test in the case of, for example, unstable tests.

The third approach we've tested is splitting tests into multiple packages that run in parallel by default. For this purpose we split tests in `sdk/pkg/networkservice/chains/nsmgr` on several packages. For testing, we have only ran the nsmgr tests and compared the execution times and found that this gives us a 10 second benefit the same on CI run. Running all tests locally also shows the same result with a 10 second benefit. But running all tests on CI showed completely different results. Tests took the same amount of time for the minimums - the maximums depend on the machine the tests were run on and on average ran even slower than before splitting on several packages.

So no solution allowed us to save time and not reduce the quality of existing tests.

**Comment by dualBreath** [comment]
While working on this issue, I also found some tests that look unstable because I see them failed on a branch without any of my changes.

`sdk/pkg/networkservice/chains/nsmgr/dns_test.go`
`Test_DNSUsecase`
Fails detected on windows, macos, linux

`sdk/pkg/networkservice/common/mechanisms/recvfd/server_test.go`
`TestRecvfd`
Fails detected on linux
