### ISSUE TITLE
Rework networkservice/refresh chain element

### ISSUE THREAD

**Issue by denis-tingaikin** [networkservicemesh/sdk#497]
## Motivation

The current implementation of refresh is not covering many possible scenarios.

## Solution

Rework refresh to support the next scenarios:

1. `refresh` from point A should refresh `refresh` from point B.  
2. `refresh` should be able to distinguish a request from the client and other `refresh`. This means that `refresh` should do the next request from the client in any case and request from the refresh should be canceled.
3. if `refresh` from point A is scheduled then in case if A triggers by B  then A should return the result of the scheduled request.
4. client's refresh should update timers for `refresh`
// TODO: Determinate and add other scenarios

**Comment by xzfc** [comment]
Investigation of bug #260 has led to discovery of a race condition in the `refreshClient.Request` code.

Reworking plan:

1. Add a stress-test to catch this race condition on the CI.
2. In order to avoid race condition, the `refreshClient.Request` should cancel the timer **before** performing `next.Client().Request()`.
3. In addition to cancelling, it should wait for ongoing request (if any), since cancelling an ongoing gRPC request is not possible.
4. As an optimization, it may return the result of ongoing request (received in the previous step) instead of performing another one. This may be done only if the request isn't changed (which is probably the case in scenario 1).
